- name: Install system packages
  become: true
  ansible.builtin.package:
    state: present
    name:
      - bash
      - bash-completion
      - curl
      - git
      - locales

- name: Enable locales
  become: true
  community.general.locale_gen:
    name:
      - en_US.UTF-8
    state: present
