- name: krew | Check if binary exists
  ansible.builtin.stat:
    path: "{{ ansible_facts['env'].HOME }}/.krew/bin/kubectl-krew"
  register: krew_stat

- name: krew | Download latest release binary and install krew plugin
  when: not krew_stat.stat.exists
  block:
    - name: krew | Create temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: dot-ansible-krew-
      register: temp_dir

    - name: krew | Download and extract latest release archive
      ansible.builtin.unarchive:
        src: "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew-linux_amd64.tar.gz"
        dest: "{{ temp_dir.path }}"
        remote_src: true
        mode: "0755"

    - name: krew | Update plugin index and install krew plugin
      ansible.builtin.command: "{{ temp_dir.path }}/krew-linux_amd64 install krew"
      args:
        creates: "{{ ansible_facts['env'].HOME }}/.krew/bin/kubectl-krew"
  always:
    - name: krew | Remove temporary directory
      ansible.builtin.file:
        path: "{{ temp_dir.path }}"
        state: absent

- name: krew | Install kubectl plugins from krew_plugins.txt
  ansible.builtin.command: "{{ ansible_facts['env'].HOME }}/.krew/bin/kubectl-krew install --no-update-index"
  args:
    stdin: "{{ lookup('file', 'krew_plugins.txt') }}"
  register: krew_install_cmd
  changed_when: "'Installed plugin:' in krew_install_cmd.stderr"

- name: krew | Copy initialization script under ~/.bashrc.d
  ansible.builtin.copy:
    src: krew.sh
    dest: "{{ ansible_facts['env'].HOME }}/.bashrc.d/krew.sh"
    mode: "0644"
